
logging:
    level:
        org:
            hibernate:
                SQL: debug
                type:
                    descriptor:
                        sql: debug
spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=UTF-8
        password: root
        username: root
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL57Dialect
                format_sql: false
        show-sql: true
    thymeleaf:
      cache: false
    messages:
      cache-duration: 1s
server:
  port: 80

